Models/Siniflar/TedarikTur.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SantiyeTakipOtomasyon.Models.Siniflar
{
    public class TedarikTur
    {
        [Key]
        public int TedarikTurId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string TurAd { get; set; }
        public ICollection<Tedarikci> Tedarikcis { get; set; }
    }
}

Controllers/TedarikTurController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SantiyeTakipOtomasyon.Models.Siniflar;

namespace SantiyeTakipOtomasyon.Controllers
{
    public class TedarikTurController : Controller
    {
        // GET: TedarikTur
        SantiyeTakipDBContext c = new SantiyeTakipDBContext();
        public ActionResult Index()
        {
            var turListesi = c.TedarikTurs.ToList();
            return View(turListesi);
        }
        [HttpPost]
        public ActionResult ModalAc()
        {
            return PartialView("TedarikTurEkle");
        }
        [HttpGet]
        public ActionResult TedarikTurEkle()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult TedarikTurEkle(TedarikTur t)
        {
            c.TedarikTurs.Add(t);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult TedarikTurSil(int id)
        {
            var tedSil = c.TedarikTurs.Find(id);
            c.TedarikTurs.Remove(tedSil);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult TedarikTurGetir(int? id)
        {
            var tedGet = c.TedarikTurs.Find(id);
            return PartialView("TedarikTurGetir", tedGet);
        }
        public ActionResult TedarikTurGuncelle(TedarikTur t)
        {
            var tur = c.TedarikTurs.Find(t.TedarikTurId);
            tur.TurAd = t.TurAd;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/TedarikTur/Index.cshtml
@using SantiyeTakipOtomasyon.Models.Siniflar
@model List<TedarikTur>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br>

<div class="card card-default">
    <div class="card-header">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11">
                <strong>Tedarik Tür İşlemleri</strong>
            </h5>
            <a href="#" class="btn btn-primary ekle col-md-1" data-target="@Url.Action("ModalAc", "TedarikTur")">Yeni Kayıt</a>
        </div>
    </div>

    <div style="margin-left:1%; margin-right:1%">
        <br />
        <table id="liste" class="table table-bordered table-hover table-sm" style="margin-top:20px">
            <thead>
                <tr>
                    <th style="width:3%">Id</th>
                    <th style="width:90%">Tür Adı</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var t in Model)
            {
                <tr>
                    <td>@t.TedarikTurId</td>
                    <td>@t.TurAd</td>
                    <td><a href="@Url.Action("TedarikTurSil", "TedarikTur")/@t.TedarikTurId" class="btn btn-danger btn-sm">Sil</a></td>
                    <td><a href="#" class="btn btn-success btn-sm guncelle" data-target="@Url.Action("TedarikTurGetir", "TedarikTur")/@t.TedarikTurId">Güncelle</a></td>
                </tr>
            }
        </table>
    </div>

    <div class="container">
        <!--Modal -->
        <div class="modal fade" id="myModalE" role="dialog">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <!--Modal -->
        <div class="modal fade" id="myModalG" role="dialog">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>

<script type="text/javascript">
    $(function () {
        $("body").on("click", ".ekle", function () {
            var url = $(this).data("target");
            $.post(url, function (data) { })
                .done(function (data) {
                    $("#myModalE .modal-body").html(data);
                    $("#myModalE").modal("show");
                })
                .fail(function () {
                    $("#myModalE .modal-body").text("Hata!!");
                    $("#myModalE").modal("show");
                })
        });
    });
    $(function () {
        $("body").on("click", ".guncelle", function () {
            var url = $(this).data("target");
            $.post(url, function (data) { })
                .done(function (data) {
                    $("#myModalG .modal-body").html(data);
                    $("#myModalG").modal("show");
                })
                .fail(function () {
                    $("#myModalG .modal-body").text("Hata!!");
                    $("#myModalG").modal("show");
                })
        });
    });

    $('#liste').DataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

Views/TedarikTur/TedarikTurEkle.cshtml
@model SantiyeTakipOtomasyon.Models.Siniflar.TedarikTur

<div class="card card-default">
    <div class="card-header bg-dark">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11" style="color:white">
                <strong>Tedarik Tür Girişi</strong>
            </h5>
        </div>
    </div>
    <div class="container">
        <form action="@Url.Action("TedarikTurEkle", "TedarikTur")" method="post">
            <hr />
            <div class="form-horizontal">
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-4 text-right" style="color:red"><b>Tedarik Türü</b></label>
                    <div class="col-sm-8">
                        <input style="width:200px;" type="text" class="form-control" name="TurAd" maxlength="100" required oninvalid="this.setCustomValidity('Bu alan boş geçilemez!')" oninput="setCustomValidity('')" />
                    </div>
                </div>
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Vazgeç</button>
                    <button class="btn btn-info">Ekle</button>
                </div>
            </div>
        </form>
    </div>
</div>

Views/TedarikTur/TedarikTurGetir.cshtml
@model SantiyeTakipOtomasyon.Models.Siniflar.TedarikTur

<div class="card card-default">
    <div class="card-header bg-dark">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11" style="color:white">
                <strong>Tedarik Tür Güncelleme</strong>
            </h5>
        </div>
    </div>
    <div class="container">
        <form action="@Url.Action("TedarikTurGuncelle", "TedarikTur")" method="post">
            <hr />
            @Html.HiddenFor(x => x.TedarikTurId)
            <div class="form-horizontal">
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-4 text-right" style="color:red"><b>Tedarik Türü</b></label>
                    <div class="col-8">
                        @Html.TextBoxFor(x => x.TurAd, new { @class = "form-control", @style = "width:200px", @maxlength = "100" })
                    </div>
                </div>
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Vazgeç</button>
                    <button class="btn btn-success">Güncelle</button>
                </div>
            </div>
        </form>
    </div>
</div>