Models/Siniflar/Proje.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SantiyeTakipOtomasyon.Models.Siniflar
{
    public class Proje
    {
        [Key]
        public int ProjeId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string ProAdi { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string ProAdres { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string ProMusavir { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string ProYapiDenetim { get; set; }

        [DataType(DataType.Date)]
        public DateTime? ProSozlesmeTarihi { get; set; }

        [DataType(DataType.Date)]
        public DateTime? ProYerTeslimTarihi { get; set; }

        [DataType(DataType.Date)]
        public DateTime? ProIseBaslamaTarihi { get; set; }

        [DataType(DataType.Date)]
        public DateTime? ProIsinBitisTarihi { get; set; }
        public int ProSozlesmeSuresi { get; set; }
        public int ProSureUzatimi1 { get; set; }
        public int ProSureUzatimi2 { get; set; }
        public int ProSureUzatimi3 { get; set; }
        public DateTime ProGeciciKabulTarihi { get; set; }
        public DateTime ProKesinKabulTarihi { get; set; }
        public decimal ProSozlesmeBedeli { get; set; }
        public decimal ProKesifArtisi1 { get; set; }
        public decimal ProKesifArtisi2 { get; set; }
        public decimal ProKesifArtisi3 { get; set; }
        public decimal ProToplamSozlesmeBedeli { get; set; }

        public int? ProDurumId { get; set; }
        public virtual ProDurum ProDurum { get; set; }
        public int IllerId { get; set; }
        public virtual Iller Iller { get; set; }
        public int IlcelerId { get; set; }
        public virtual Ilceler Ilceler { get; set; }

        public ICollection<Fatura> Faturas { get; set; }
        public ICollection<Personel> Personels { get; set; }
        public ICollection<Odeme> Odemes { get; set; }
    }
}

Controllers/ProjeController.cs
using SantiyeTakipOtomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SantiyeTakipOtomasyon.Controllers
{
    public class ProjeController : Controller
    {
        // GET: Proje
        SantiyeTakipDBContext c = new SantiyeTakipDBContext();
        public ActionResult Index()
        {
            var liste = c.Projes.OrderBy(p => p.ProjeId).ToList();
            return View(liste);
        }
        [HttpPost]
        public ActionResult ModalAc()
        {
            List<SelectListItem> ilListe = (from t in c.Illers.ToList()
                                            select new SelectListItem
                                            {
                                                Text = t.Sehir,
                                                Value = t.IllerId.ToString()
                                            }).ToList();
            ViewBag.iList = ilListe;

            List<SelectListItem> durListe = (from d in c.ProDurums.ToList()
                                            select new SelectListItem
                                            {
                                                Text = d.Durum,
                                                Value = d.ProDurumId.ToString()
                                            }).ToList();
            ViewBag.dList = durListe;

            return PartialView("ProjeEkle");
        }
        [HttpGet]
        public ActionResult ProjeEkle()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult ProjeEkle(Proje p)
        {
            if(p.ProSozlesmeTarihi == null)
            {

            }
            c.Projes.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult IlceListe(int IlId)
        {
            List<Ilceler> ilceList = c.Ilcelers.Where(i => i.IllerId == IlId).OrderBy(i => i.IlceAdi).ToList();

            List<SelectListItem> ilceListe = (from i in ilceList
                                              select new SelectListItem
                                              {
                                                  Text = i.IlceAdi,
                                                  Value = i.IlcelerId.ToString()
                                              }).ToList();

            return Json(ilceListe, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ProjeGetir(int? id)
        {
            var pGet = c.Projes.Find(id);

            List<SelectListItem> ilListe = (from t in c.Illers.ToList()
                                            select new SelectListItem
                                            {
                                                Text = t.Sehir,
                                                Value = t.IllerId.ToString()
                                            }).ToList();
            ViewBag.iList = ilListe;

            List<SelectListItem> durListe = (from d in c.ProDurums.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = d.Durum,
                                                 Value = d.ProDurumId.ToString()
                                             }).ToList();
            ViewBag.dList = durListe;

            var il = c.Projes.Where(x => x.ProjeId == id).FirstOrDefault();
            List<Ilceler> ilceList = c.Ilcelers.Where(i => i.IllerId == il.IllerId).OrderBy(i => i.IlceAdi).ToList();

            List<SelectListItem> ilceListe = (from i in ilceList
                                              select new SelectListItem
                                              {
                                                  Text = i.IlceAdi,
                                                  Value = i.IlcelerId.ToString()
                                              }).ToList();

            ViewBag.ilcList = ilceListe;

            return PartialView("ProjeGetir", pGet);
        }
        public ActionResult ProjeGuncelle(Proje p)
        {
            var pro = c.Projes.Find(p.ProjeId);
            pro.ProAdi = p.ProAdi;
            pro.ProAdres = p.ProAdres;
            pro.IllerId = p.IllerId;
            pro.IlcelerId = p.IlcelerId;
            pro.ProMusavir = p.ProMusavir;
            pro.ProYapiDenetim = p.ProYapiDenetim;
            pro.ProSozlesmeTarihi = p.ProSozlesmeTarihi;
            pro.ProYerTeslimTarihi = p.ProYerTeslimTarihi;
            pro.ProIseBaslamaTarihi = p.ProIseBaslamaTarihi;
            pro.ProIsinBitisTarihi = p.ProIsinBitisTarihi;
            pro.ProSozlesmeSuresi = p.ProSozlesmeSuresi;
            pro.ProSozlesmeBedeli = p.ProSozlesmeBedeli;
            pro.ProDurumId = p.ProDurumId;
            pro.ProSureUzatimi1 = p.ProSureUzatimi1;
            pro.ProSureUzatimi2 = p.ProSureUzatimi2;
            pro.ProSureUzatimi3 = p.ProSureUzatimi3;
            pro.ProKesifArtisi1 = p.ProKesifArtisi1;
            pro.ProKesifArtisi2 = p.ProKesifArtisi2;
            pro.ProKesifArtisi3 = p.ProKesifArtisi3;
            c.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult ProjeBilgi(int? id)
        {
            ViewBag.ProAdi = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProAdi).FirstOrDefault();
            ViewBag.ProAdres = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProAdres).FirstOrDefault();
            ViewBag.Sehir = c.Projes.Where(p => p.ProjeId == id).Select(x => x.Iller.Sehir).FirstOrDefault();
            ViewBag.Ilce = c.Projes.Where(p => p.ProjeId == id).Select(x => x.Ilceler.IlceAdi).FirstOrDefault();
            ViewBag.ProMusavir = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProMusavir).FirstOrDefault();
            ViewBag.ProYapiDenetim = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProYapiDenetim).FirstOrDefault();
            ViewBag.ProSozlesmeTarihi = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProSozlesmeTarihi).FirstOrDefault();
            ViewBag.ProYerTeslimTarihi = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProYerTeslimTarihi).FirstOrDefault();
            ViewBag.ProIseBaslamaTarihi = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProIseBaslamaTarihi).FirstOrDefault();
            ViewBag.ProIsinBitisTarihi = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProIsinBitisTarihi).FirstOrDefault();
            ViewBag.ProSozlesmeSuresi = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProSozlesmeSuresi).FirstOrDefault();
            ViewBag.ProSozlesmeBedeli = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProSozlesmeBedeli).FirstOrDefault();
            ViewBag.ProDurum = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProDurum.Durum).FirstOrDefault();

            ViewBag.ProSureUzatimi1 = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProSureUzatimi1).FirstOrDefault();
            ViewBag.ProSureUzatimi2 = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProSureUzatimi2).FirstOrDefault();
            ViewBag.ProSureUzatimi3 = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProSureUzatimi3).FirstOrDefault();

            ViewBag.ProKesifArtisi1 = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProKesifArtisi1).FirstOrDefault();
            ViewBag.ProKesifArtisi2 = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProKesifArtisi2).FirstOrDefault();
            ViewBag.ProKesifArtisi3 = c.Projes.Where(p => p.ProjeId == id).Select(x => x.ProKesifArtisi3).FirstOrDefault();

            return PartialView("ProjeBilgi");
        }
    }
}

Controllers/TedarikciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SantiyeTakipOtomasyon.Models.Siniflar;

namespace SantiyeTakipOtomasyon.Controllers
{
    public class TedarikciController : Controller
    {
        // GET: Tedarikci
        SantiyeTakipDBContext c = new SantiyeTakipDBContext();
        public ActionResult Index()
        {
            var liste = c.Tedarikcis.OrderBy(x => x.TedarikciId).ToList();
            return View(liste);
        }
        [HttpPost]
        public ActionResult ModalAc()
        {
            List<SelectListItem> turListe = (from t in c.TedarikTurs.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = t.TurAd,
                                                 Value = t.TedarikTurId.ToString()
                                             }).ToList();
            ViewBag.tList = turListe;

            List<SelectListItem> ilListe = (from t in c.Illers.ToList()
                                            select new SelectListItem
                                            {
                                                Text = t.Sehir,
                                                Value = t.IllerId.ToString()
                                            }).ToList();

            ViewBag.iList = ilListe;

            return PartialView("TedarikciEkle");
        }
        [HttpGet]
        public ActionResult TedarikciEkle()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult TedarikciEkle(Tedarikci p)
        {
            c.Tedarikcis.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult IlceListe(int IlId)
        {
            List<Ilceler> ilceList = c.Ilcelers.Where(i => i.IllerId == IlId).OrderBy(i => i.IlceAdi).ToList();

            List<SelectListItem> ilceListe = (from i in ilceList
                                              select new SelectListItem
                                              {
                                                  Text = i.IlceAdi,
                                                  Value = i.IlcelerId.ToString()
                                              }).ToList();

            return Json(ilceListe, JsonRequestBehavior.AllowGet);
        }
        public ActionResult TedarikciGetir(int? id)
        {
            List<SelectListItem> turListe = (from tl in c.TedarikTurs.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = tl.TurAd,
                                                 Value = tl.TedarikTurId.ToString()
                                             }).ToList();
            ViewBag.tList = turListe;

            List<SelectListItem> ilListe = (from i in c.Illers.ToList()
                                            select new SelectListItem
                                            {
                                                Text = i.Sehir,
                                                Value = i.IllerId.ToString()
                                            }).ToList();

            ViewBag.iList = ilListe;

            var il = c.Tedarikcis.Where(x => x.TedarikciId == id).FirstOrDefault();
            List<Ilceler> ilceList = c.Ilcelers.Where(i => i.IllerId == il.IllerId).OrderBy(i => i.IlceAdi).ToList();

            List<SelectListItem> ilceListe = (from i in ilceList
                                              select new SelectListItem
                                              {
                                                  Text = i.IlceAdi,
                                                  Value = i.IlcelerId.ToString()
                                              }).ToList();

            ViewBag.ilcList = ilceListe;

            var tedGet = c.Tedarikcis.Find(id);
            return PartialView("TedarikciGetir", tedGet);
        }
        public ActionResult TedarikciGuncelle(Tedarikci p)
        {
            var ted = c.Tedarikcis.Find(p.TedarikciId);
            ted.TedKod = p.TedKod;
            ted.TedFirma = p.TedFirma;
            ted.TedIlgiliKisi = p.TedIlgiliKisi;
            ted.TedAdres = p.TedAdres;
            ted.IllerId = p.IllerId;
            ted.IlcelerId = p.IlcelerId;
            ted.TedTelefon = p.TedTelefon;
            ted.TedGsm = p.TedGsm;
            ted.TedEposta = p.TedEposta;
            ted.TedarikturId = p.TedarikturId;
            ted.TedKonu = p.TedKonu;
            c.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Views/Proje/Index.cshtml
@using SantiyeTakipOtomasyon.Models.Siniflar
@model List<Proje>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />

<div class="card card-default">
    <div class="card-header">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11">
                <strong>Proje İşlemleri</strong>
            </h5>
            <a href="#" class="btn btn-primary ekle col-md-1" data-target="@Url.Action("ModalAc", "Proje")">Yeni Kayıt</a>
        </div>
    </div>

    <!--Proje Listesi-->
    <div style="margin-left:1%; margin-right:1%">
        <br />
        <table id="liste" class="table table-bordered table-hover table-sm" style="margin-top:20px;">
            <thead>
                <tr>
                    <th style="width:5%"><small><strong>Proje Id</strong></small></th>
                    <th style="width:20%"><small><strong>Proje Adı</strong></small></th>
                    <th style="width:15%"><small><strong>Proje Adres</strong></small></th>
                    <th style="width:20%"><small><strong>Müşavir</strong></small></th>
                    <th style="width:20%"><small><strong>Yapı Denetim</strong></small></th>
                    <th style="width:5%"><small><strong>Sözleşme Tarihi</strong></small></th>
                    <th style="width:5%"><small><strong>Yer Teslim Tarihi</strong></small></th>
                    <th style="width:10%"><small><strong>İşe Başlama Tarihi</strong></small></th>
                    <th style="width:5%"><small><strong>İşin Bitiş Tarihi</strong></small></th>
                    <th style="width:10%"><small><strong>Sözleşme Bedeli(TL)</strong></small></th>
                    <th style="width:10%"><small><strong>Proje Durum</strong></small></th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var p in Model)
            {
                <tr>
                    <td class="bilgi" style="cursor:pointer;cursor:hand;" data-toggle="modal" data-target="@Url.Action("ProjeBilgi", "Proje")/@p.ProjeId">
                        <small>@p.ProjeId</small>
                    </td>
                    <td class="bilgi" style="cursor:pointer;cursor:hand;" data-toggle="modal" data-target="@Url.Action("ProjeBilgi", "Proje")/@p.ProjeId">
                        <small>@p.ProAdi</small>
                    </td>
                    <td class="bilgi" style="cursor:pointer;cursor:hand;" data-toggle="modal" data-target="@Url.Action("ProjeBilgi", "Proje")/@p.ProjeId">
                        <small>@p.ProAdres @p.Ilceler.IlceAdi/@p.Iller.Sehir</small>
                    </td>
                    <td class="bilgi" style="cursor:pointer;cursor:hand;" data-toggle="modal" data-target="@Url.Action("ProjeBilgi", "Proje")/@p.ProjeId">
                        <small>@p.ProMusavir</small>
                    </td>
                    <td class="bilgi" style="cursor:pointer;cursor:hand;" data-toggle="modal" data-target="@Url.Action("ProjeBilgi", "Proje")/@p.ProjeId">
                        <small>@p.ProYapiDenetim</small>
                    </td>
                    <td class="bilgi" style="cursor:pointer;cursor:hand;" data-toggle="modal" data-target="@Url.Action("ProjeBilgi", "Proje")/@p.ProjeId">
                        <small>@string.Format("{0:dd/MM/yyyy}", p.ProSozlesmeTarihi)</small>
                    </td>
                    <td class="bilgi" style="cursor:pointer;cursor:hand;" data-toggle="modal" data-target="@Url.Action("ProjeBilgi", "Proje")/@p.ProjeId">
                        <small>@string.Format("{0:dd/MM/yyyy}", p.ProYerTeslimTarihi)</small>
                    </td>
                    <td class="bilgi" style="cursor:pointer;cursor:hand;" data-toggle="modal" data-target="@Url.Action("ProjeBilgi", "Proje")/@p.ProjeId">
                        <small>@string.Format("{0:dd/MM/yyyy}", p.ProIseBaslamaTarihi)</small>
                    </td>
                    <td class="bilgi" style="cursor:pointer;cursor:hand;" data-toggle="modal" data-target="@Url.Action("ProjeBilgi", "Proje")/@p.ProjeId">
                        <small>@string.Format("{0:dd/MM/yyyy}", p.ProIsinBitisTarihi)</small>
                    </td>
                    <td class="bilgi" style="cursor:pointer;cursor:hand;text-align:right" data-toggle="modal" data-target="@Url.Action("ProjeBilgi", "Proje")/@p.ProjeId">
                        <small>@p.ProSozlesmeBedeli.ToString("N")</small>
                    </td>
                    <td class="bilgi" style="cursor:pointer;cursor:hand;" data-toggle="modal" data-target="@Url.Action("ProjeBilgi", "Proje")/@p.ProjeId">
                        <small>@p.ProDurum.Durum</small>
                    </td>
                    <td><a href="#" class="btn btn-success btn-sm guncelle" data-target="@Url.Action("ProjeGetir", "Proje")/@p.ProjeId">Güncelle</a></td>
                </tr>
            }
        </table>
    </div>

    <div class="container">
        <!--Proje Ekle Modal -->
        <div class="modal fade" id="myModalE" role="dialog">
            <div class="modal-dialog modal-xl modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <!--Proje Güncelle Modal -->
        <div class="modal fade" id="myModalG" role="dialog">
            <div class="modal-dialog modal-xl modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <!--Proje Bilgi Modal -->
        <div class="modal fade" id="myModalB" role="dialog">
            <div class="modal-dialog modal-xl modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>


<script type="text/javascript">
    $(function () {
        $("body").on("click", ".ekle", function () {
            var url = $(this).data("target");
            $.post(url, function (data) { })
                .done(function (data) {
                    $("#myModalE .modal-body").html(data);
                    $("#myModalE").modal("show");
                })
                .fail(function () {
                    $("#myModalE .modal-body").text("Hata!!");
                    $("#myModalE").modal("show");
                })
        });
    });
    $(function () {
        $("body").on("click", ".guncelle", function () {
            var url = $(this).data("target");
            $.post(url, function (data) { })
                .done(function (data) {
                    $("#myModalG .modal-body").html(data);
                    $("#myModalG").modal("show");
                })
                .fail(function () {
                    $("#myModalG .modal-body").text("Hata!!");
                    $("#myModalG").modal("show");
                })
        });
    });
    $(function () {
        $("body").on("click", ".bilgi", function () {
            var url = $(this).data("target");
            $.post(url, function (data) { })
                .done(function (data) {
                    $("#myModalB .modal-body").html(data);
                    $("#myModalB").modal("show");
                })
                .fail(function () {
                    $("#myModalB .modal-body").text("Hata!!");
                    $("#myModalB").modal("show");
                })
        });
    });

    $('#liste').DataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

Views/Proje/ProjeEkle.cshtml
@model SantiyeTakipOtomasyon.Models.Siniflar.Proje

<div class="card card-default">
    <div class="card-header bg-dark">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11" style="color:white">
                <strong>Proje Girişi</strong>
            </h5>
        </div>
    </div>
    <div class="container">
        <form action="@Url.Action("ProjeEkle", "Proje")" method="post">
            <hr />
            <div class="form-horizontal">
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-2 text-right" style="color:red"><b>Proje Adı</b></label>
                    <div class="col-md-3">
                        <input type="text" id="ProAdi" name="ProAdi" placeholder="Proje Adını Giriniz" class="form-control" style="width:200%;" maxlength="100" required oninvalid="this.setCustomValidity('Bu alan boş geçilemez!')" oninput="setCustomValidity('')" />
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-2 text-right" style="color:red"><b>Proje Adresi</b></label>
                    <div class="col-md-3">
                        <input type="text" id="ProAdres" name="ProAdres" placeholder="Proje Adresini Giriniz" class="form-control" style="width:200%;" maxlength="100" required oninvalid="this.setCustomValidity('Bu alan boş geçilemez!')" oninput="setCustomValidity('')" />
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-2 text-right" style="color:red"><b>İl/İlçe</b></label>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => x.IllerId, (List<SelectListItem>)ViewBag.iList, "------- Seçiniz -------", new { @class = "form-control", @style = "width:90%", @required = "" })
                    </div>
                    <div class="col-md-7">
                        @Html.DropDownListFor(x => x.IlcelerId, Enumerable.Empty<SelectListItem>(), new { @class = "form-control", @style = "width:45%", @required = "" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-2 text-right" ><b>Müşavir</b></label>
                    <div class="col-md-3">
                        <input type="text" id="ProMusavir" name="ProMusavir" placeholder="Müşavir Adını Giriniz" class="form-control" style="width:200%;" maxlength="100"  />
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-2 text-right" ><b>Yapı Denetim</b></label>
                    <div class="col-md-3">
                        <input type="text" id="ProYapiDenetim" name="ProYapiDenetim" placeholder="Yapı Denetim Firmasını Giriniz" class="form-control" style="width:200%;" maxlength="100" />
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-2 text-right" ><b>Sözleşme Tarihi</b></label>
                    <div class="col-md-2">
                        <input type="date" id="ProSozlesmeTarihi" name="ProSozlesmeTarihi" class="form-control" style="width:110%;" />
                    </div>
                    <label class="col-form-label-sm col-md-2 text-right" ><b>Yer Teslim Tarihi</b></label>
                    <div class="col-md-2">
                        <input type="date" id="ProYerTeslimTarihi" name="ProYerTeslimTarihi" class="form-control" style="width:110%;" />
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-2 text-right" ><b>İşe Başlama Tarihi</b></label>
                    <div class="col-md-2">
                        <input type="date" id="ProIseBaslamaTarihi" name="ProIseBaslamaTarihi" class="form-control" style="width:110%;" />
                    </div>
                    <label class="col-form-label-sm col-md-2 text-right" ><b>İşin Bitiş Tarihi</b></label>
                    <div class="col-md-2">
                        <input type="date" id="ProIsinBitisTarihi" name="ProIseBitisTarihi" class="form-control" style="width:110%;" />
                    </div>
                    <label class="col-form-label-sm col-md-2 text-right" ><b>Sözleşme Süresi</b></label>
                    <div class="col-md-2">
                        <input type="text" id="ProSozlesmeSuresi" name="ProSozlesmeSuresi" class="form-control" style="width:60%; text-align:right" />
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-2 text-right" ><b>Sözleşme Bedeli</b></label>
                    <div class="col-md-2">
                        <input type="text" id="ProSozlesmeBedeli" name="ProSozlesmeBedeli" class="form-control" style="width:100%; text-align:right" />
                    </div>
                    <label class="col-form-label-sm col-md-2 text-right" style="color:red"><b>Proje Durumu</b></label>
                    <div class="col-md-2">
                        @Html.DropDownListFor(x => x.ProDurumId, (List<SelectListItem>)ViewBag.dList, "----- Seçiniz -----", new { @class = "form-control", @style = "width:130%", @required = "" })
                    </div>
                </div>
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Vazgeç</button>
                    <button class="btn btn-info">Ekle</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#IllerId').change(function () {
            var IlId = $(this).val();
            var IlceL = $('#IlcelerId');
            IlceL.empty();
            $.ajax({
                url: '@Url.Action("IlceListe","Tedarikci")',
                type: 'POST',
                dataType: 'json',
                data: { 'IlId': IlId },
                success: function (data) {
                    $.each(data, function (index, option) {
                        IlceL.append('<option value=' + option.Value + '>' + option.Text + '</option>');
                    });
                }
            });
        });
    });
</script>