Models/Siniflar/MalHizmet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SantiyeTakipOtomasyon.Models.Siniflar
{
    public class MalHizmet
    {
        [Key]
        public int MalHizmetId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string MalHizmetAdi { get; set; }

        public int BirimId { get; set; }
        public virtual Birim Birim { get; set; }
        public int MalHizmetGrupId { get; set; }
        public virtual MalHizmetGrup MalHizmetGrup { get; set; }
        public ICollection<FaturaDetay> FaturaDetays { get; set; }
    }
}

Controllers/MalHizmetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SantiyeTakipOtomasyon.Models.Siniflar;

namespace SantiyeTakipOtomasyon.Controllers
{
    public class MalHizmetController : Controller
    {
        SantiyeTakipDBContext c = new SantiyeTakipDBContext();
        // GET: MalHizmet
        public ActionResult Index()
        {
            var liste = c.MalHizmets.ToList();
            return View(liste);
        }
        [HttpPost]
        public ActionResult ModalAc()
        {
            List<SelectListItem> malHizmetListe = (from m in c.MalHizmetGrups.ToList()
                                                   select new SelectListItem
                                                   {
                                                       Text = m.MalHizmetGrupAdi,
                                                       Value = m.MalHizmetGrupId.ToString()
                                                   }).ToList();

            List<SelectListItem> birimListe = (from b in c.Birims.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = b.BirimAdi,
                                                   Value = b.BirimId.ToString()
                                               }).ToList();

            ViewBag.mhListe = malHizmetListe;
            ViewBag.brmListe = birimListe;

            return PartialView("MalHizmetEkle");
        }
        [HttpGet]
        public ActionResult MalHizmetEkle()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult MalHizmetEkle(MalHizmet p)
        {
            c.MalHizmets.Add(p);
            c.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult MalHizmetGetir(int id)
        {
            List<SelectListItem> malHizmetListe = (from m in c.MalHizmetGrups.ToList()
                                                   select new SelectListItem
                                                   {
                                                       Text = m.MalHizmetGrupAdi,
                                                       Value = m.MalHizmetGrupId.ToString()
                                                   }).ToList();

            List<SelectListItem> birimListe = (from b in c.Birims.ToList()
                                                   select new SelectListItem
                                                   {
                                                       Text = b.BirimAdi,
                                                       Value = b.BirimId.ToString()
                                                   }).ToList();

            ViewBag.mhListe = malHizmetListe;
            ViewBag.brmListe = birimListe;
            var mlHiz = c.MalHizmets.Find(id);

            return PartialView("MalHizmetGetir", mlHiz);
        }
        public ActionResult MalHizmetGuncelle(MalHizmet p)
        {
            var mlhmt = c.MalHizmets.Find(p.MalHizmetId);
            mlhmt.MalHizmetAdi = p.MalHizmetAdi;
            mlhmt.MalHizmetGrupId = p.MalHizmetGrupId;
            mlhmt.BirimId = p.BirimId;
            c.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Views/MalHizmet/Index.cshtml
@using SantiyeTakipOtomasyon.Models.Siniflar
@model List<MalHizmet>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />

<div class="card card-default">
    <div class="card-header">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11">
                <strong>Mal/Hizmet İşlemleri</strong>
            </h5>
            <a href="#" class="btn btn-primary ekle col-md-1" data-target="@Url.Action("ModalAc", "MalHizmet")">Yeni Kayıt</a>
        </div>
    </div>

    <!--Proje Listesi-->
    <div style="margin-left:1%; margin-right:1%">
        <br />
        <table id="liste" class="table table-bordered table-hover table-sm" style="margin-top:20px;">
            <thead>
                <tr>
                    <th style="width:5%"><small><strong>Id</strong></small></th>
                    <th style="width:40%"><small><strong>Mal/Hizmet Adı</strong></small></th>
                    <th style="width:20%"><small><strong>Birim</strong></small></th>
                    <th style="width:20%"><small><strong>Mal/Hizmet Grubu</strong></small></th>
                    <th style="width:5%"></th>
                </tr>
            </thead>
            @foreach (var m in Model)
            {
                <tr>
                    <td><small>@m.MalHizmetId</small></td>
                    <td><small>@m.MalHizmetAdi</small></td>
                    <td><small>@m.Birim.BirimAdi</small></td>
                    <td><small>@m.MalHizmetGrup.MalHizmetGrupAdi</small></td>
                    <td><a href="#" class="btn btn-sm btn-success guncelle" data-target="@Url.Action("MalHizmetGetir", "MalHizmet")/@m.MalHizmetId">Güncelle</a></td>
                </tr>
            }
        </table>
    </div>

    <div class="container">
        <!--Proje Ekle Modal -->
        <div class="modal fade" id="myModalE" role="dialog">
            <div class="modal-dialog modal-lg modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <!--Proje Güncelle Modal -->
        <div class="modal fade" id="myModalG" role="dialog">
            <div class="modal-dialog modal-lg modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <!--Proje Bilgi Modal -->
        <div class="modal fade" id="myModalB" role="dialog">
            <div class="modal-dialog modal-lg modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>

<script type="text/javascript">
    $(function () {
        $("body").on("click", ".ekle", function () {
            var url = $(this).data("target");
            $.post(url, function (data) { })
                .done(function (data) {
                    $("#myModalE .modal-body").html(data);
                    $("#myModalE").modal("show");
                })
                .fail(function () {
                    $("#myModalE .modal-body").text("Hata!!");
                    $("#myModalE").modal("show");
                })
        });
    });
    $(function () {
        $("body").on("click", ".guncelle", function () {
            var url = $(this).data("target");
            $.post(url, function (data) { })
                .done(function (data) {
                    $("#myModalG .modal-body").html(data);
                    $("#myModalG").modal("show");
                })
                .fail(function () {
                    $("#myModalG .modal-body").text("Hata!!");
                    $("#myModalG").modal("show");
                })
        });
    });
    $(function () {
        $("body").on("click", ".bilgi", function () {
            var url = $(this).data("target");
            $.post(url, function (data) { })
                .done(function (data) {
                    $("#myModalB .modal-body").html(data);
                    $("#myModalB").modal("show");
                })
                .fail(function () {
                    $("#myModalB .modal-body").text("Hata!!");
                    $("#myModalB").modal("show");
                })
        });
    });

    $('#liste').DataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

Views/MalHizmet/MalHizmetEkle.cshtml
@model SantiyeTakipOtomasyon.Models.Siniflar.MalHizmet

<div class="card card-default">
    <div class="card-header bg-dark">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11" style="color:white">
                <strong>Mal/Hizmet Girişi</strong>
            </h5>
        </div>
    </div>
    <div class="container">
        <form action="@Url.Action("MalHizmetEkle", "MalHizmet")" method="post">
            <hr />
            <div class="form-horizontal">
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-4 text-right" style="color:red"><b>Mal/Hizmet Grubu</b></label>
                    <div class="col-sm-8">
                        @Html.DropDownListFor(x => x.MalHizmetGrupId, (List<SelectListItem>)ViewBag.mhListe, "------- Seçiniz -------", new { @class = "form-control", @style = "width:200px", @required = "" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-4 text-right" style="color:red"><b>Mal/Hizmet Adı</b></label>
                    <div class="col-sm-8">
                        <input style="width:300px;" type="text" class="form-control" name="MalHizmetAdi" maxlength="100" required oninvalid="this.setCustomValidity('Bu alan boş geçilemez!')" oninput="setCustomValidity('')" />
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-4 text-right" style="color:red"><b>Birim</b></label>
                    <div class="col-sm-8">
                        @Html.DropDownListFor(x => x.BirimId, (List<SelectListItem>)ViewBag.brmListe, "------- Seçiniz -------", new { @class = "form-control", @style = "width:200px", @required = "" })
                    </div>
                </div>
                <br />
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Vazgeç</button>
                    <button class="btn btn-info">Ekle</button>
                </div>
            </div>
        </form>
    </div>
</div>

Views/MalHizmet/MalHizmetGetir.cshtml
@model SantiyeTakipOtomasyon.Models.Siniflar.MalHizmet

<div class="card card-default">
    <div class="card-header bg-dark">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11" style="color:white">
                <strong>Mal/Hizmet Güncelleme</strong>
            </h5>
        </div>
    </div>
    <div class="container">
        <form action="@Url.Action("MalHizmetGuncelle", "MalHizmet")" method="post">
            <hr />
            @Html.HiddenFor(x => x.MalHizmetId)
            <div class="form-horizontal">
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-4 text-right" style="color:red"><b>Mal/Hizmet Grubu</b></label>
                    <div class="col-8">
                        @Html.DropDownListFor(x => x.MalHizmetGrupId, (List<SelectListItem>)ViewBag.mhListe, new { @class = "form-control", @style = "width:200px" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-4 text-right" style="color:red"><b>Mal/Hizmet Adı</b></label>
                    <div class="col-8">
                        @Html.TextBoxFor(x => x.MalHizmetAdi, new { @class = "form-control", @style = "width:300px", @maxlength = "100" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-4 text-right" style="color:red"><b>Mal/Hizmet Grubu</b></label>
                    <div class="col-8">
                        @Html.DropDownListFor(x => x.BirimId, (List<SelectListItem>)ViewBag.brmListe, new { @class = "form-control", @style = "width:200px" })
                    </div>
                </div>
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Vazgeç</button>
                    <button class="btn btn-success">Güncelle</button>
                </div>
            </div>
        </form>
    </div>
</div>