Models/Siniflar/Odeme.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SantiyeTakipOtomasyon.Models.Siniflar
{
    public class Odeme
    {
        [Key]
        public int OdemeId { get; set; }
        public DateTime OdemeTarihi { get; set; }
        public decimal OdemeTutari { get; set; }
        public int TedarikciId { get; set; }
        public virtual Tedarikci Tedarikci { get; set; }
        public int OdemeSekliId { get; set; }
        public virtual OdemeSekli OdemeSekli { get; set; }
        public int OdemeTuruId { get; set; }
        public virtual OdemeTuru OdemeTuru { get; set; }
        public int ProjeId { get; set; }
        public virtual Proje Proje { get; set; }
    }
}

Controllers/OdemeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SantiyeTakipOtomasyon.Models.Siniflar;

namespace SantiyeTakipOtomasyon.Controllers
{
    public class OdemeController : Controller
    {
        SantiyeTakipDBContext c = new SantiyeTakipDBContext();
        // GET: Odeme
        public ActionResult Index()
        {
            return View("Index");
        }
        public ActionResult ProjeSecim()
        {
            List<SelectListItem> proListe = (from p in c.Projes.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = p.ProAdi,
                                                 Value = p.ProjeId.ToString()
                                             }).ToList();

            ViewBag.pList = proListe;

            return PartialView("ProjeSecim");
        }
        public ActionResult ListeGetir(int? id)
        {
            var liste = c.Odemes.OrderBy(o => o.OdemeId).Where(x => x.ProjeId == id).ToList();
            var ProjeAdi = c.Projes.Where(p => p.ProjeId == id).Select(a => a.ProAdi).FirstOrDefault();

            ViewBag.proAd = ProjeAdi;
            ViewBag.projeId = id;

            return View("Index", liste);
        }
        [HttpPost]
        public ActionResult ModalAc(int id)
        {
            List<SelectListItem> firmaListe = (from f in c.Tedarikcis.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = f.TedFirma,
                                                   Value = f.TedarikciId.ToString()
                                               }).ToList();

            List<SelectListItem> odemeTurListe = (from o in c.OdemeTurus.ToList()
                                                  select new SelectListItem
                                                  {
                                                      Text = o.TurAdi,
                                                      Value = o.OdemeTuruId.ToString()
                                                  }).ToList();

            List<SelectListItem> odemeSekliListe = (from o in c.OdemeSeklis.ToList()
                                                    select new SelectListItem
                                                    {
                                                        Text = o.OdSekliAdi,
                                                        Value = o.OdemeSekliId.ToString()
                                                    }).ToList();

            ViewBag.fListe = firmaListe;
            ViewBag.oTListe = odemeTurListe;
            ViewBag.oSListe = odemeSekliListe;
            ViewBag.projeId = id;

            return PartialView("OdemeEkle");
        }
        [HttpGet]
        public ActionResult OdemeEkle()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult OdemeEkle(Odeme p)
        {
            c.Odemes.Add(p);
            c.SaveChanges();
            var projeId = p.ProjeId;
            return RedirectToAction("ListeGetir", new { id = projeId });
        }
        public ActionResult OdemeGetir(int? id)
        {
            var odemeGetir = c.Odemes.Find(id);
            var proId = c.Odemes.Where(x => x.OdemeId == id).Select(p => p.ProjeId).FirstOrDefault();

            List<SelectListItem> firmaListe = (from f in c.Tedarikcis.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = f.TedFirma,
                                                   Value = f.TedarikciId.ToString()
                                               }).ToList();

            List<SelectListItem> odemeTurListe = (from o in c.OdemeTurus.ToList()
                                                  select new SelectListItem
                                                  {
                                                      Text = o.TurAdi,
                                                      Value = o.OdemeTuruId.ToString()
                                                  }).ToList();

            List<SelectListItem> odemeSekliListe = (from o in c.OdemeSeklis.ToList()
                                                    select new SelectListItem
                                                    {
                                                        Text = o.OdSekliAdi,
                                                        Value = o.OdemeSekliId.ToString()
                                                    }).ToList();

            ViewBag.fListe = firmaListe;
            ViewBag.oTListe = odemeTurListe;
            ViewBag.oSListe = odemeSekliListe;
            ViewBag.projeId = proId;

            return PartialView("OdemeGetir", odemeGetir);
        }
        public ActionResult OdemeGuncelle(Odeme p)
        {
            var odeme = c.Odemes.Find(p.OdemeId);
            odeme.TedarikciId = p.TedarikciId;
            odeme.OdemeTuruId = p.OdemeTuruId;
            odeme.OdemeSekliId = p.OdemeSekliId;
            odeme.OdemeTarihi = p.OdemeTarihi;
            odeme.OdemeTutari = p.OdemeTutari;
            c.SaveChanges();

            var projeId = p.ProjeId;
            return RedirectToAction("ListeGetir", new { id = projeId });
        }
        public ActionResult OdemeSil(int id)
        {
            var projeId = c.Odemes.Where(x => x.OdemeId == id).Select(p => p.ProjeId).FirstOrDefault();
            var odemeSil = c.Odemes.Find(id);
            c.Odemes.Remove(odemeSil);
            c.SaveChanges();

            return RedirectToAction("ListeGetir", new { id = projeId });
        }
    }
}

Controllers/ProjeSecimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SantiyeTakipOtomasyon.Controllers
{
    public class ProjeSecimController : Controller
    {
        // GET: ProjeSecim
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/Odeme/Index.cshtml
@using SantiyeTakipOtomasyon.Models.Siniflar
@model List<Odeme>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<div class="card bg-secondary text-white" style="height:40px">
    <div class="card-body align-items-center d-flex justify-content-center">Proje Adı : @ViewBag.proAd</div>
</div>
<br>

<div class="card card-default">
    <div class="card-header">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11">
                <strong>Ödeme İşlemleri</strong>
            </h5>
            <a href="#" class="btn btn-primary ekle col-md-1" data-target="@Url.Action("ModalAc", "Odeme")/@ViewBag.projeId">Yeni Kayıt</a>
        </div>
    </div>

    <!--Ödeme Listesi-->
    <div style="margin-left:1%; margin-right:1%">
        <br />
        <table id="liste" class="table table-bordered table-hover table-sm">
            <thead>
                <tr>
                    <th style="width:5%">Id</th>
                    <th style="width:40%">Firma</th>
                    <th style="width:10%">Ödeme Türü</th>
                    <th style="width:10%">Ödeme Şekli</th>
                    <th style="width:10%">Ödeme Tarihi</th>
                    <th style="width:10%">Ödeme Tutarı</th>
                    <th style="width:2%"></th>
                    <th style="width:5%"></th>
                </tr>
            </thead>
            @foreach (var p in Model)
            {
                <tr>
                    <td class="" style="cursor:pointer;cursor:hand;" data-toggle="" data-target="">@p.OdemeId</td>
                    <td class="" style="cursor:pointer;cursor:hand;" data-toggle="" data-target="">@p.Tedarikci.TedFirma</td>
                    <td class="" style="cursor:pointer;cursor:hand;" data-toggle="" data-target="">@p.OdemeTuru.TurAdi</td>
                    <td class="" style="cursor:pointer;cursor:hand;" data-toggle="" data-target="">@p.OdemeSekli.OdSekliAdi</td>
                    <td class="" style="cursor:pointer;cursor:hand; text-align:center;" data-toggle="" data-target="">@string.Format("{0:dd/MM/yyyy}", p.OdemeTarihi)</td>
                    <td class="" style="cursor:pointer;cursor:hand; text-align:right;" data-toggle="" data-target="">@p.OdemeTutari.ToString("N")</td>
                    <td><a href="@Url.Action("OdemeSil", "Odeme")/@p.OdemeId" class="btn btn-danger btn-sm">Sil</a></td>
                    <td><a href="#" class="btn btn-success btn-sm guncelle" data-target="@Url.Action("OdemeGetir", "Odeme")/@p.OdemeId">Güncelle</a></td>
                </tr>
            }
        </table>
    </div>
</div>

<div class="container">
    <!--Ekle Modal -->
    <div class="modal fade" id="myModalE" role="dialog">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <!--Güncelle Modal -->
    <div class="modal fade" id="myModalG" role="dialog">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <!--Bilgi Modal -->
    <div class="modal fade" id="myModalB" role="dialog">
        <div class="modal-dialog modal-xl modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>
</div>

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>

<script type="text/javascript">
    $(function () {
        $("body").on("click", ".ekle", function () {
            var url = $(this).data("target");
            $.post(url, function (data) { })
                .done(function (data) {
                    $("#myModalE .modal-body").html(data);
                    $("#myModalE").modal("show");
                })
                .fail(function () {
                    $("#myModalE .modal-body").text("Hata!!");
                    $("#myModalE").modal("show");
                })
        });
    });
    $(function () {
        $("body").on("click", ".guncelle", function () {
            var url = $(this).data("target");
            $.post(url, function (data) { })
                .done(function (data) {
                    $("#myModalG .modal-body").html(data);
                    $("#myModalG").modal("show");
                })
                .fail(function () {
                    $("#myModalG .modal-body").text("Hata!!");
                    $("#myModalG").modal("show");
                })
        });
    });
    $(function () {
        $("body").on("click", ".bilgi", function () {
            var url = $(this).data("target");
            $.post(url, function (data) { })
                .done(function (data) {
                    $("#myModalB .modal-body").html(data);
                    $("#myModalB").modal("show");
                })
                .fail(function () {
                    $("#myModalB .modal-body").text("Hata!!");
                    $("#myModalB").modal("show");
                })
        });
    });

    $('#liste').DataTable({
        "language": {

            "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Turkish.json"

        }
    });
</script>

Views/Odeme/OdemeEkle.cshtml
@model SantiyeTakipOtomasyon.Models.Siniflar.Odeme

<div class="card card-default">
    <div class="card-header bg-dark">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11" style="color:white">
                <strong>Ödeme Giriş</strong>
            </h5>
        </div>
    </div>
    <div class="container">
        <form action="@Url.Action("OdemeEkle", "Odeme")" method="post">
            <hr />
            <input hidden id="ProjeId" name="ProjeId" value="@ViewBag.projeId" />
            <div class="form-horizontal">
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-3 text-right" style="color:red"><b>Firma</b></label>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => x.TedarikciId, (List<SelectListItem>)ViewBag.fListe, "------------------------ Seçiniz ------------------------", new { @class = "form-control", @style = "width:300%", @required = "" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-3 text-right" style="color:red"><b>Ödeme Türü</b></label>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => x.OdemeTuruId, (List<SelectListItem>)ViewBag.oTListe, "--- Seçiniz ---", new { @class = "form-control", @style = "width:100%", @required = "" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-3 text-right" style="color:red"><b>Ödeme Şekli</b></label>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => x.OdemeSekliId, (List<SelectListItem>)ViewBag.oSListe, "--- Seçiniz ---", new { @class = "form-control", @style = "width:100%", @required = "" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-3 text-right" style="color:red"><b>Ödeme Tarihi</b></label>
                    <div class="col-md-3">
                        <input type="date" id="OdemeTarihi" name="OdemeTarihi" class="form-control" style="width:110%;" />
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-3 text-right" style="color:red"><b>Ödeme Tutarı</b></label>
                    <div class="col-md-2">
                        <input type="text" id="OdemeTutari" name="OdemeTutari" class="form-control" style="width:150%; text-align:right" required oninvalid="this.setCustomValidity('Bu alan boş geçilemez!')" oninput="setCustomValidity('')"  />
                    </div>
                </div>
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Vazgeç</button>
                    <button class="btn btn-info">Ekle</button>
                </div>
            </div>
        </form>
    </div>
</div>

Views/Odeme/OdemeGetir.cshtml
@model SantiyeTakipOtomasyon.Models.Siniflar.Odeme

<div class="card card-default">
    <div class="card-header bg-dark">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11" style="color:white">
                <strong>Ödeme Güncelleme</strong>
            </h5>
        </div>
    </div>
    <div class="container">
        <form action="@Url.Action("OdemeGuncelle", "Odeme")" method="post">
            <hr />
            @Html.HiddenFor(x => x.ProjeId, new { @value = ViewBag.projeId })
            @Html.HiddenFor(x => x.OdemeId)
            <div class="form-horizontal">
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-3 text-right"><b>Firma</b></label>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => x.TedarikciId, (List<SelectListItem>)ViewBag.fListe, new { @class = "form-control", @style = "width:300%" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-3 text-right"><b>Ödeme Türü</b></label>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => x.OdemeTuruId, (List<SelectListItem>)ViewBag.oTListe, new { @class = "form-control", @style = "width:100%" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-3 text-right"><b>Ödeme Şekli</b></label>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => x.OdemeSekliId, (List<SelectListItem>)ViewBag.oSListe, new { @class = "form-control", @style = "width:100%" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-3 text-right"><b>Ödeme Tarihi</b></label>
                    <div class="col-md-3">
                        @Html.TextBoxFor(x => x.OdemeTarihi, "{0:yyyy-MM-dd}", new { @class = "form-control", @style = "width:110%;", @type = "date" })
                    </div>
                </div>
                <br />
                <div class="container form-group-sm row">
                    <label class="col-form-label-sm col-md-3 text-right"><b>Ödeme Tutarı</b></label>
                    <div class="col-md-2">
                        @Html.TextBoxFor(x => x.OdemeTutari, new { @class = "form-control", @style = "width:150%; text-align:right;" })
                    </div>
                </div>
                <br />
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Vazgeç</button>
                    <button class="btn btn-success">Güncelle</button>
                </div>
            </div>
        </form>
    </div>
</div>

Views/Odeme/ProjeSecim.cshtml
@model SantiyeTakipOtomasyon.Models.Siniflar.Proje

<div class="card card-default">
    <div class="card-header bg-dark">
        <div class="row">
            <h5 class="card-title mb-sm-1 col-md-11" style="color:white">
                <strong>Proje Seçimi</strong>
            </h5>
        </div>
    </div>
    <div class="container">
        <div class="form-horizontal">
            <br />
            <div class="container form-group-sm row">
                <label class="col-form-label-sm col-md-2 text-right"><b>Proje Adı</b></label>
                <div class="col-md-3">
                    @Html.DropDownList("selection", (List<SelectListItem>)ViewBag.pList, "----------------------- Seçiniz ----------------------", new { @class = "form-control", @style = "width:400px", @name = "ProjeId", @id = "ProjeId" })
                </div>
            </div>
            <br />
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Vazgeç</button>
                <button id="Sec" class="btn btn-info">Seç</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#Sec').on('click', function (e) {
            e.preventDefault();

            var ProId = $("#ProjeId").val();
            var url = '@Url.Action("ListeGetir","Odeme")/' + ProId;
            window.location.href = url;
        });
    });
</script>